package com.example.finance.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.DynamicUpdate;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "accounts")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamicUpdate
public class Account extends BaseEntity {

    /*
     * Account number is generated by the application.
     *
     * It must never be accepted from AccountCreateRequestDTO
     * or changed through AccountUpdateRequestDTO.
     */
    @Column(
            name = "account_number",
            nullable = false,
            unique = true,
            updatable = false,
            length = 20
    )
    private String accountNumber;

    /*
     * Many accounts can belong to one customer.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(
            name = "customer_id",
            nullable = false,
            foreignKey = @ForeignKey(name = "fk_account_customer")
    )
    private Customer customer;

    @Enumerated(EnumType.STRING)
    @Column(
            name = "account_type",
            nullable = false,
            length = 20
    )
    private AccountType accountType;

    /*
     * Balance is controlled by financial transactions.
     *
     * It must NOT be directly updated through a normal
     * Account PUT request.
     */
    @Column(
            name = "balance",
            nullable = false,
            precision = 19,
            scale = 2
    )
    @Builder.Default
    private BigDecimal balance = BigDecimal.ZERO;

    @Enumerated(EnumType.STRING)
    @Column(
            name = "status",
            nullable = false,
            length = 20
    )
    @Builder.Default
    private AccountStatus status = AccountStatus.ACTIVE;

    /*
     * One account can have many transactions.
     *
     * mappedBy = "account" refers to the Account field
     * inside Transaction.
     */
    @OneToMany(
            mappedBy = "account",
            fetch = FetchType.LAZY
    )
    @Builder.Default
    private List<Transaction> transactions = new ArrayList<>();

}