package com.example.finance.entity;

import java.math.BigDecimal;

import com.example.finance.entity.enums.TransactionDirection;
import com.example.finance.entity.enums.TransactionStatus;
import com.example.finance.entity.enums.TransactionType;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.NamedQuery;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name = "transactions")
@NamedQuery(name = "Transaction.findByAccountIdAndTransactionType", query = """
		SELECT t
		FROM Transaction t
		WHERE t.account.id = :accountId
		  AND t.transactionType = :transactionType
		ORDER BY t.createdAt DESC
		""")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Transaction extends BaseEntity {

	/*
	 * Unique transaction reference generated by application.
	 *
	 * Example: TXN-A12B34C56D78
	 */
	@Column(name = "transaction_reference", nullable = false, unique = true, updatable = false, length = 30)
	private String transactionReference;

	/*
	 * Account associated with this transaction.
	 */
	@ManyToOne(fetch = FetchType.LAZY, optional = false)
	@JoinColumn(name = "account_id", nullable = false, foreignKey = @ForeignKey(name = "fk_transaction_account"))
	private Account account;

	/*
	 * Transaction amount.
	 */
	@Column(name = "amount", nullable = false, precision = 19, scale = 2)
	private BigDecimal amount;

	/*
	 * Balance before this transaction.
	 */
	@Column(name = "balance_before", nullable = false, precision = 19, scale = 2)
	private BigDecimal balanceBefore;

	/*
	 * Balance after this transaction.
	 */
	@Column(name = "balance_after", nullable = false, precision = 19, scale = 2)
	private BigDecimal balanceAfter;

	/*
	 * DEPOSIT / WITHDRAWAL / TRANSFER
	 */
	@Enumerated(EnumType.STRING)
	@Column(name = "transaction_type", nullable = false, length = 20)
	private TransactionType transactionType;

	/*
	 * CREDIT / DEBIT
	 */
	@Enumerated(EnumType.STRING)
	@Column(name = "direction", nullable = false, length = 10)
	private TransactionDirection direction;

	/*
	 * PENDING / SUCCESS / FAILED
	 */
	@Enumerated(EnumType.STRING)
	@Column(name = "status", nullable = false, length = 20)
	@Builder.Default
	private TransactionStatus status = TransactionStatus.PENDING;

	/*
	 * Used only for transfers.
	 *
	 * The debit and credit transaction belonging to the same transfer share this
	 * reference.
	 *
	 * Example:
	 *
	 * TRF-A12B34C56D78
	 */
	@Column(name = "transfer_reference", updatable = false, length = 30)
	private String transferReference;

	/*
	 * Optional business description.
	 */
	@Column(name = "description", length = 255)
	private String description;
}
