package com.example.finance.responceDto;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import com.example.finance.entity.AccountStatus;
import com.example.finance.entity.AccountType;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AccountResponseDTO {

    private Long id;

    /*
     * Generated by the application.
     * This is returned to the client but is never
     * accepted from AccountRequestDTO.
     */
    private String accountNumber;

    /*
     * We return customerId instead of exposing
     * the complete Customer entity.
     */
    private Long customerId;

    private AccountType accountType;

    /*
     * Balance is read-only through this API.
     * It is changed through financial transactions.
     */
    private BigDecimal balance;

    private AccountStatus status;

    /*
     * Optimistic locking version.
     */
    private Long version;

    /*
     * Auditing information inherited from BaseEntity.
     */
    private LocalDateTime createdAt;

    private LocalDateTime updatedAt;

    private String createdBy;

    private String updatedBy;
}
